# 最新のCompose Specification（version指定は非推奨）
# Docker Compose v2.x 以降対応

services:
  wire-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    container_name: wire-dev
    volumes:
      # ホストのプロジェクトディレクトリを直接マウント
      - .:/workspace
      # Goモジュールのキャッシュ（パフォーマンス向上）
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  go-mod-cache:
    driver: local
    labels:
      description: "Goモジュールキャッシュ"
  go-build-cache:
    driver: local
    labels:
      description: "Goビルドキャッシュ"
